### ISSUE TITLE
Making surf easy

### ISSUE THREAD

**Issue by abhishekdeshkar** [fluffyst/Surftimer#140]
Hi,

I'm a beginner in surfing. I'm still struggling to complete some of the tier-1 surf maps.

I mostly play surf for fun and I don't care about developing surfing skills.

The problem is that I lose speed after crossing 3-4 ramps and I cannot enjoy entire map.

I'm thinking to develop a plugin which can give players enough push/boost so that they can reach to next ramp even if they have got less speed. Some sort of boost from each ramp.

Any ideas how do I do this ?

I thought of modifying player's velocity but that doesn't work because we don't know how much velocity is actually required to go to next ramp.

Any inputs ?

Thanks!

**Comment by devDrk** [comment]
Changing the velocity wont do anything since its a constant value. You need to add a style that will change the users velocity to add an extra hundred or so, that seems like what you want to do. Also you might want to just put more time into surfing to get better, instead of just taking an easy way but anyway gl

**Comment by abhishekdeshkar** [comment]
@devDrk I understand your point and it is totally valid. But I cannot invest so much time in surf.

I mainly play surf for fun after my office hours. And I'm already tired at that time so.

Do you have any suggestion apart from adding extra velocity ?

I thought of giving boost when player leaves ramp.

If you have any suggestions then let me know.

Thanks!
